//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escritorio.ServidorCS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://Servicio/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicio/", ConfigurationName="ServidorCS.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://Servicio/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/Crear_Usuario", ReplyAction="*")]
        Escritorio.ServidorCS.Crear_UsuarioResponse Crear_Usuario(Escritorio.ServidorCS.Crear_UsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://Servicio/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/Iniciar_Sesion", ReplyAction="*")]
        Escritorio.ServidorCS.Iniciar_SesionResponse Iniciar_Sesion(Escritorio.ServidorCS.Iniciar_SesionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Leer_UsuariosResult del espacio de nombres http://Servicio/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/Leer_Usuarios", ReplyAction="*")]
        Escritorio.ServidorCS.Leer_UsuariosResponse Leer_Usuarios(Escritorio.ServidorCS.Leer_UsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/Eliminar_Usuario", ReplyAction="*")]
        void Eliminar_Usuario(int carnet);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://Servicio/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/Actualizar_Usuario", ReplyAction="*")]
        Escritorio.ServidorCS.Actualizar_UsuarioResponse Actualizar_Usuario(Escritorio.ServidorCS.Actualizar_UsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento pedido del espacio de nombres http://Servicio/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/Crear_Pedido", ReplyAction="*")]
        Escritorio.ServidorCS.Crear_PedidoResponse Crear_Pedido(Escritorio.ServidorCS.Crear_PedidoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Leer_pedidosResult del espacio de nombres http://Servicio/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/Leer_pedidos", ReplyAction="*")]
        Escritorio.ServidorCS.Leer_pedidosResponse Leer_pedidos(Escritorio.ServidorCS.Leer_pedidosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/Eliminar_pedido", ReplyAction="*")]
        void Eliminar_pedido(int id_pedido);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento i_pedido del espacio de nombres http://Servicio/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicio/Actualizar_Pedido", ReplyAction="*")]
        Escritorio.ServidorCS.Actualizar_PedidoResponse Actualizar_Pedido(Escritorio.ServidorCS.Actualizar_PedidoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Crear_UsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Crear_Usuario", Namespace="http://Servicio/", Order=0)]
        public Escritorio.ServidorCS.Crear_UsuarioRequestBody Body;
        
        public Crear_UsuarioRequest() {
        }
        
        public Crear_UsuarioRequest(Escritorio.ServidorCS.Crear_UsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Servicio/")]
    public partial class Crear_UsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int carnet;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apellido;
        
        public Crear_UsuarioRequestBody() {
        }
        
        public Crear_UsuarioRequestBody(int carnet, string nombre, string apellido) {
            this.carnet = carnet;
            this.nombre = nombre;
            this.apellido = apellido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Crear_UsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Crear_UsuarioResponse", Namespace="http://Servicio/", Order=0)]
        public Escritorio.ServidorCS.Crear_UsuarioResponseBody Body;
        
        public Crear_UsuarioResponse() {
        }
        
        public Crear_UsuarioResponse(Escritorio.ServidorCS.Crear_UsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Servicio/")]
    public partial class Crear_UsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Crear_UsuarioResult;
        
        public Crear_UsuarioResponseBody() {
        }
        
        public Crear_UsuarioResponseBody(int Crear_UsuarioResult) {
            this.Crear_UsuarioResult = Crear_UsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Iniciar_SesionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Iniciar_Sesion", Namespace="http://Servicio/", Order=0)]
        public Escritorio.ServidorCS.Iniciar_SesionRequestBody Body;
        
        public Iniciar_SesionRequest() {
        }
        
        public Iniciar_SesionRequest(Escritorio.ServidorCS.Iniciar_SesionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Servicio/")]
    public partial class Iniciar_SesionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int carnet;
        
        public Iniciar_SesionRequestBody() {
        }
        
        public Iniciar_SesionRequestBody(string nombre, int carnet) {
            this.nombre = nombre;
            this.carnet = carnet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Iniciar_SesionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Iniciar_SesionResponse", Namespace="http://Servicio/", Order=0)]
        public Escritorio.ServidorCS.Iniciar_SesionResponseBody Body;
        
        public Iniciar_SesionResponse() {
        }
        
        public Iniciar_SesionResponse(Escritorio.ServidorCS.Iniciar_SesionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Servicio/")]
    public partial class Iniciar_SesionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Escritorio.ServidorCS.ArrayOfString Iniciar_SesionResult;
        
        public Iniciar_SesionResponseBody() {
        }
        
        public Iniciar_SesionResponseBody(Escritorio.ServidorCS.ArrayOfString Iniciar_SesionResult) {
            this.Iniciar_SesionResult = Iniciar_SesionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Leer_UsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Leer_Usuarios", Namespace="http://Servicio/", Order=0)]
        public Escritorio.ServidorCS.Leer_UsuariosRequestBody Body;
        
        public Leer_UsuariosRequest() {
        }
        
        public Leer_UsuariosRequest(Escritorio.ServidorCS.Leer_UsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Leer_UsuariosRequestBody {
        
        public Leer_UsuariosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Leer_UsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Leer_UsuariosResponse", Namespace="http://Servicio/", Order=0)]
        public Escritorio.ServidorCS.Leer_UsuariosResponseBody Body;
        
        public Leer_UsuariosResponse() {
        }
        
        public Leer_UsuariosResponse(Escritorio.ServidorCS.Leer_UsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Servicio/")]
    public partial class Leer_UsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Escritorio.ServidorCS.ArrayOfString Leer_UsuariosResult;
        
        public Leer_UsuariosResponseBody() {
        }
        
        public Leer_UsuariosResponseBody(Escritorio.ServidorCS.ArrayOfString Leer_UsuariosResult) {
            this.Leer_UsuariosResult = Leer_UsuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Actualizar_UsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Actualizar_Usuario", Namespace="http://Servicio/", Order=0)]
        public Escritorio.ServidorCS.Actualizar_UsuarioRequestBody Body;
        
        public Actualizar_UsuarioRequest() {
        }
        
        public Actualizar_UsuarioRequest(Escritorio.ServidorCS.Actualizar_UsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Servicio/")]
    public partial class Actualizar_UsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int carnet;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apellido;
        
        public Actualizar_UsuarioRequestBody() {
        }
        
        public Actualizar_UsuarioRequestBody(int carnet, string nombre, string apellido) {
            this.carnet = carnet;
            this.nombre = nombre;
            this.apellido = apellido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Actualizar_UsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Actualizar_UsuarioResponse", Namespace="http://Servicio/", Order=0)]
        public Escritorio.ServidorCS.Actualizar_UsuarioResponseBody Body;
        
        public Actualizar_UsuarioResponse() {
        }
        
        public Actualizar_UsuarioResponse(Escritorio.ServidorCS.Actualizar_UsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Actualizar_UsuarioResponseBody {
        
        public Actualizar_UsuarioResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Crear_PedidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Crear_Pedido", Namespace="http://Servicio/", Order=0)]
        public Escritorio.ServidorCS.Crear_PedidoRequestBody Body;
        
        public Crear_PedidoRequest() {
        }
        
        public Crear_PedidoRequest(Escritorio.ServidorCS.Crear_PedidoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Servicio/")]
    public partial class Crear_PedidoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pedido;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int cantidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int carnet;
        
        public Crear_PedidoRequestBody() {
        }
        
        public Crear_PedidoRequestBody(string pedido, int cantidad, int carnet) {
            this.pedido = pedido;
            this.cantidad = cantidad;
            this.carnet = carnet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Crear_PedidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Crear_PedidoResponse", Namespace="http://Servicio/", Order=0)]
        public Escritorio.ServidorCS.Crear_PedidoResponseBody Body;
        
        public Crear_PedidoResponse() {
        }
        
        public Crear_PedidoResponse(Escritorio.ServidorCS.Crear_PedidoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Servicio/")]
    public partial class Crear_PedidoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Crear_PedidoResult;
        
        public Crear_PedidoResponseBody() {
        }
        
        public Crear_PedidoResponseBody(int Crear_PedidoResult) {
            this.Crear_PedidoResult = Crear_PedidoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Leer_pedidosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Leer_pedidos", Namespace="http://Servicio/", Order=0)]
        public Escritorio.ServidorCS.Leer_pedidosRequestBody Body;
        
        public Leer_pedidosRequest() {
        }
        
        public Leer_pedidosRequest(Escritorio.ServidorCS.Leer_pedidosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Leer_pedidosRequestBody {
        
        public Leer_pedidosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Leer_pedidosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Leer_pedidosResponse", Namespace="http://Servicio/", Order=0)]
        public Escritorio.ServidorCS.Leer_pedidosResponseBody Body;
        
        public Leer_pedidosResponse() {
        }
        
        public Leer_pedidosResponse(Escritorio.ServidorCS.Leer_pedidosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Servicio/")]
    public partial class Leer_pedidosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Escritorio.ServidorCS.ArrayOfString Leer_pedidosResult;
        
        public Leer_pedidosResponseBody() {
        }
        
        public Leer_pedidosResponseBody(Escritorio.ServidorCS.ArrayOfString Leer_pedidosResult) {
            this.Leer_pedidosResult = Leer_pedidosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Actualizar_PedidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Actualizar_Pedido", Namespace="http://Servicio/", Order=0)]
        public Escritorio.ServidorCS.Actualizar_PedidoRequestBody Body;
        
        public Actualizar_PedidoRequest() {
        }
        
        public Actualizar_PedidoRequest(Escritorio.ServidorCS.Actualizar_PedidoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Servicio/")]
    public partial class Actualizar_PedidoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int i_id_pedido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string i_pedido;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int i_cantidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int i_carnet;
        
        public Actualizar_PedidoRequestBody() {
        }
        
        public Actualizar_PedidoRequestBody(int i_id_pedido, string i_pedido, int i_cantidad, int i_carnet) {
            this.i_id_pedido = i_id_pedido;
            this.i_pedido = i_pedido;
            this.i_cantidad = i_cantidad;
            this.i_carnet = i_carnet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Actualizar_PedidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Actualizar_PedidoResponse", Namespace="http://Servicio/", Order=0)]
        public Escritorio.ServidorCS.Actualizar_PedidoResponseBody Body;
        
        public Actualizar_PedidoResponse() {
        }
        
        public Actualizar_PedidoResponse(Escritorio.ServidorCS.Actualizar_PedidoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Actualizar_PedidoResponseBody {
        
        public Actualizar_PedidoResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Escritorio.ServidorCS.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Escritorio.ServidorCS.Service1Soap>, Escritorio.ServidorCS.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Escritorio.ServidorCS.Crear_UsuarioResponse Escritorio.ServidorCS.Service1Soap.Crear_Usuario(Escritorio.ServidorCS.Crear_UsuarioRequest request) {
            return base.Channel.Crear_Usuario(request);
        }
        
        public int Crear_Usuario(int carnet, string nombre, string apellido) {
            Escritorio.ServidorCS.Crear_UsuarioRequest inValue = new Escritorio.ServidorCS.Crear_UsuarioRequest();
            inValue.Body = new Escritorio.ServidorCS.Crear_UsuarioRequestBody();
            inValue.Body.carnet = carnet;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            Escritorio.ServidorCS.Crear_UsuarioResponse retVal = ((Escritorio.ServidorCS.Service1Soap)(this)).Crear_Usuario(inValue);
            return retVal.Body.Crear_UsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Escritorio.ServidorCS.Iniciar_SesionResponse Escritorio.ServidorCS.Service1Soap.Iniciar_Sesion(Escritorio.ServidorCS.Iniciar_SesionRequest request) {
            return base.Channel.Iniciar_Sesion(request);
        }
        
        public Escritorio.ServidorCS.ArrayOfString Iniciar_Sesion(string nombre, int carnet) {
            Escritorio.ServidorCS.Iniciar_SesionRequest inValue = new Escritorio.ServidorCS.Iniciar_SesionRequest();
            inValue.Body = new Escritorio.ServidorCS.Iniciar_SesionRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.carnet = carnet;
            Escritorio.ServidorCS.Iniciar_SesionResponse retVal = ((Escritorio.ServidorCS.Service1Soap)(this)).Iniciar_Sesion(inValue);
            return retVal.Body.Iniciar_SesionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Escritorio.ServidorCS.Leer_UsuariosResponse Escritorio.ServidorCS.Service1Soap.Leer_Usuarios(Escritorio.ServidorCS.Leer_UsuariosRequest request) {
            return base.Channel.Leer_Usuarios(request);
        }
        
        public Escritorio.ServidorCS.ArrayOfString Leer_Usuarios() {
            Escritorio.ServidorCS.Leer_UsuariosRequest inValue = new Escritorio.ServidorCS.Leer_UsuariosRequest();
            inValue.Body = new Escritorio.ServidorCS.Leer_UsuariosRequestBody();
            Escritorio.ServidorCS.Leer_UsuariosResponse retVal = ((Escritorio.ServidorCS.Service1Soap)(this)).Leer_Usuarios(inValue);
            return retVal.Body.Leer_UsuariosResult;
        }
        
        public void Eliminar_Usuario(int carnet) {
            base.Channel.Eliminar_Usuario(carnet);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Escritorio.ServidorCS.Actualizar_UsuarioResponse Escritorio.ServidorCS.Service1Soap.Actualizar_Usuario(Escritorio.ServidorCS.Actualizar_UsuarioRequest request) {
            return base.Channel.Actualizar_Usuario(request);
        }
        
        public void Actualizar_Usuario(int carnet, string nombre, string apellido) {
            Escritorio.ServidorCS.Actualizar_UsuarioRequest inValue = new Escritorio.ServidorCS.Actualizar_UsuarioRequest();
            inValue.Body = new Escritorio.ServidorCS.Actualizar_UsuarioRequestBody();
            inValue.Body.carnet = carnet;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            Escritorio.ServidorCS.Actualizar_UsuarioResponse retVal = ((Escritorio.ServidorCS.Service1Soap)(this)).Actualizar_Usuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Escritorio.ServidorCS.Crear_PedidoResponse Escritorio.ServidorCS.Service1Soap.Crear_Pedido(Escritorio.ServidorCS.Crear_PedidoRequest request) {
            return base.Channel.Crear_Pedido(request);
        }
        
        public int Crear_Pedido(string pedido, int cantidad, int carnet) {
            Escritorio.ServidorCS.Crear_PedidoRequest inValue = new Escritorio.ServidorCS.Crear_PedidoRequest();
            inValue.Body = new Escritorio.ServidorCS.Crear_PedidoRequestBody();
            inValue.Body.pedido = pedido;
            inValue.Body.cantidad = cantidad;
            inValue.Body.carnet = carnet;
            Escritorio.ServidorCS.Crear_PedidoResponse retVal = ((Escritorio.ServidorCS.Service1Soap)(this)).Crear_Pedido(inValue);
            return retVal.Body.Crear_PedidoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Escritorio.ServidorCS.Leer_pedidosResponse Escritorio.ServidorCS.Service1Soap.Leer_pedidos(Escritorio.ServidorCS.Leer_pedidosRequest request) {
            return base.Channel.Leer_pedidos(request);
        }
        
        public Escritorio.ServidorCS.ArrayOfString Leer_pedidos() {
            Escritorio.ServidorCS.Leer_pedidosRequest inValue = new Escritorio.ServidorCS.Leer_pedidosRequest();
            inValue.Body = new Escritorio.ServidorCS.Leer_pedidosRequestBody();
            Escritorio.ServidorCS.Leer_pedidosResponse retVal = ((Escritorio.ServidorCS.Service1Soap)(this)).Leer_pedidos(inValue);
            return retVal.Body.Leer_pedidosResult;
        }
        
        public void Eliminar_pedido(int id_pedido) {
            base.Channel.Eliminar_pedido(id_pedido);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Escritorio.ServidorCS.Actualizar_PedidoResponse Escritorio.ServidorCS.Service1Soap.Actualizar_Pedido(Escritorio.ServidorCS.Actualizar_PedidoRequest request) {
            return base.Channel.Actualizar_Pedido(request);
        }
        
        public void Actualizar_Pedido(int i_id_pedido, string i_pedido, int i_cantidad, int i_carnet) {
            Escritorio.ServidorCS.Actualizar_PedidoRequest inValue = new Escritorio.ServidorCS.Actualizar_PedidoRequest();
            inValue.Body = new Escritorio.ServidorCS.Actualizar_PedidoRequestBody();
            inValue.Body.i_id_pedido = i_id_pedido;
            inValue.Body.i_pedido = i_pedido;
            inValue.Body.i_cantidad = i_cantidad;
            inValue.Body.i_carnet = i_carnet;
            Escritorio.ServidorCS.Actualizar_PedidoResponse retVal = ((Escritorio.ServidorCS.Service1Soap)(this)).Actualizar_Pedido(inValue);
        }
    }
}
